### ISSUE TITLE
How can you identify the customer? 

### ISSUE THREAD

**Issue by AMBTN** [Craftpeak/woocommerce-prevent-repeat-purchases#1]
Dear Developer, 

How can you identify the customer? Must the customer login? 
The customers can purchase without creating an account on the checkout page. How is the plugin working by this case? 

Thank you, 
Alex

**Comment by JulienMelissas** [comment]
Hello @AMBTN, unfortunately we don't provide support for the plugins we list on GitHub, so you will have to read the code to understand what is going on. Feel free to fork and modify for your needs, and submit bugfixes or enhancements as pull requests.

This plugin is meant to be used on sites where customers MUST have an account in order to purchase, so it keeps track of repeat purchases based on if the logged-in user has bought the product before. Hope this helps.
