### ISSUE TITLE
It only works when the order is status (Processing Order)

### ISSUE THREAD

**Issue by williams42** [Craftpeak/woocommerce-prevent-repeat-purchases#4]
In my store, orders automatically go from pending payment status to on hold. The plugin works only when I change the order status to (Processing Order), Is there any way it works for orders in On Hold Order status?

**Comment by JulienMelissas** [comment]
Hello there @williams42 - this plugin uses the native WooCommerce function `wc_customer_bought_product` which you would have to modify/hook into so that it would count an "On Hold" order as purchased a product. This would be out of scope for this plugin, however, since it's not default behavior, but I would love to see a PR if you do add some type of filter that allows you to define the order statuses that count towards the previous purchasing of a product if you manage to figure it out.

Hope that helps!
